'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WS_DRG_COMPLAIN
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WS_DRG_COMPLAINSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WS_DRG_COMPLAIN
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private INSERT_DATAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GET_DATA_COMPLAINOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SV_CONNECT_COMPLAINOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ADD_DATAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.POST_CENTER.My.MySettings.Default.POST_CENTER_WS_DRG_COMPLAIN_WS_DRG_COMPLAIN
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event INSERT_DATACompleted As INSERT_DATACompletedEventHandler
        
        '''<remarks/>
        Public Event GET_DATA_COMPLAINCompleted As GET_DATA_COMPLAINCompletedEventHandler
        
        '''<remarks/>
        Public Event SV_CONNECT_COMPLAINCompleted As SV_CONNECT_COMPLAINCompletedEventHandler
        
        '''<remarks/>
        Public Event ADD_DATACompleted As ADD_DATACompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync()
            Me.HelloWorldAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INSERT_DATA", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function INSERT_DATA(ByVal xml As String, ByVal PDF_TRADER As String, ByVal XML_TRADER As String, ByVal CITIZEN_ID As String, ByVal SOURCH As String, ByVal SOURCH_ID As String, ByVal LOT_CHK As String, ByVal IDA As String) As Object
            Dim results() As Object = Me.Invoke("INSERT_DATA", New Object() {xml, PDF_TRADER, XML_TRADER, CITIZEN_ID, SOURCH, SOURCH_ID, LOT_CHK, IDA})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub INSERT_DATAAsync(ByVal xml As String, ByVal PDF_TRADER As String, ByVal XML_TRADER As String, ByVal CITIZEN_ID As String, ByVal SOURCH As String, ByVal SOURCH_ID As String, ByVal LOT_CHK As String, ByVal IDA As String)
            Me.INSERT_DATAAsync(xml, PDF_TRADER, XML_TRADER, CITIZEN_ID, SOURCH, SOURCH_ID, LOT_CHK, IDA, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub INSERT_DATAAsync(ByVal xml As String, ByVal PDF_TRADER As String, ByVal XML_TRADER As String, ByVal CITIZEN_ID As String, ByVal SOURCH As String, ByVal SOURCH_ID As String, ByVal LOT_CHK As String, ByVal IDA As String, ByVal userState As Object)
            If (Me.INSERT_DATAOperationCompleted Is Nothing) Then
                Me.INSERT_DATAOperationCompleted = AddressOf Me.OnINSERT_DATAOperationCompleted
            End If
            Me.InvokeAsync("INSERT_DATA", New Object() {xml, PDF_TRADER, XML_TRADER, CITIZEN_ID, SOURCH, SOURCH_ID, LOT_CHK, IDA}, Me.INSERT_DATAOperationCompleted, userState)
        End Sub
        
        Private Sub OnINSERT_DATAOperationCompleted(ByVal arg As Object)
            If (Not (Me.INSERT_DATACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent INSERT_DATACompleted(Me, New INSERT_DATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_DATA_COMPLAIN", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GET_DATA_COMPLAIN(ByVal SYSTEM_ID As String) As COMPLAIN_MA()
            Dim results() As Object = Me.Invoke("GET_DATA_COMPLAIN", New Object() {SYSTEM_ID})
            Return CType(results(0),COMPLAIN_MA())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GET_DATA_COMPLAINAsync(ByVal SYSTEM_ID As String)
            Me.GET_DATA_COMPLAINAsync(SYSTEM_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GET_DATA_COMPLAINAsync(ByVal SYSTEM_ID As String, ByVal userState As Object)
            If (Me.GET_DATA_COMPLAINOperationCompleted Is Nothing) Then
                Me.GET_DATA_COMPLAINOperationCompleted = AddressOf Me.OnGET_DATA_COMPLAINOperationCompleted
            End If
            Me.InvokeAsync("GET_DATA_COMPLAIN", New Object() {SYSTEM_ID}, Me.GET_DATA_COMPLAINOperationCompleted, userState)
        End Sub
        
        Private Sub OnGET_DATA_COMPLAINOperationCompleted(ByVal arg As Object)
            If (Not (Me.GET_DATA_COMPLAINCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GET_DATA_COMPLAINCompleted(Me, New GET_DATA_COMPLAINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SV_CONNECT_COMPLAIN", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SV_CONNECT_COMPLAIN(ByVal fileds As fileds_COMPLAIN_CLASS) As String
            Dim results() As Object = Me.Invoke("SV_CONNECT_COMPLAIN", New Object() {fileds})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SV_CONNECT_COMPLAINAsync(ByVal fileds As fileds_COMPLAIN_CLASS)
            Me.SV_CONNECT_COMPLAINAsync(fileds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SV_CONNECT_COMPLAINAsync(ByVal fileds As fileds_COMPLAIN_CLASS, ByVal userState As Object)
            If (Me.SV_CONNECT_COMPLAINOperationCompleted Is Nothing) Then
                Me.SV_CONNECT_COMPLAINOperationCompleted = AddressOf Me.OnSV_CONNECT_COMPLAINOperationCompleted
            End If
            Me.InvokeAsync("SV_CONNECT_COMPLAIN", New Object() {fileds}, Me.SV_CONNECT_COMPLAINOperationCompleted, userState)
        End Sub
        
        Private Sub OnSV_CONNECT_COMPLAINOperationCompleted(ByVal arg As Object)
            If (Not (Me.SV_CONNECT_COMPLAINCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SV_CONNECT_COMPLAINCompleted(Me, New SV_CONNECT_COMPLAINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ADD_DATA", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ADD_DATA(ByVal xml As String, ByVal PDF_TRADER As String, ByVal XML_TRADER As String, ByVal CITIZEN_ID As String, ByVal SOURCH As String, ByVal SOURCH_ID As String, ByVal LOT_CHK As String, ByVal IDA As String) As Object
            Dim results() As Object = Me.Invoke("ADD_DATA", New Object() {xml, PDF_TRADER, XML_TRADER, CITIZEN_ID, SOURCH, SOURCH_ID, LOT_CHK, IDA})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ADD_DATAAsync(ByVal xml As String, ByVal PDF_TRADER As String, ByVal XML_TRADER As String, ByVal CITIZEN_ID As String, ByVal SOURCH As String, ByVal SOURCH_ID As String, ByVal LOT_CHK As String, ByVal IDA As String)
            Me.ADD_DATAAsync(xml, PDF_TRADER, XML_TRADER, CITIZEN_ID, SOURCH, SOURCH_ID, LOT_CHK, IDA, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ADD_DATAAsync(ByVal xml As String, ByVal PDF_TRADER As String, ByVal XML_TRADER As String, ByVal CITIZEN_ID As String, ByVal SOURCH As String, ByVal SOURCH_ID As String, ByVal LOT_CHK As String, ByVal IDA As String, ByVal userState As Object)
            If (Me.ADD_DATAOperationCompleted Is Nothing) Then
                Me.ADD_DATAOperationCompleted = AddressOf Me.OnADD_DATAOperationCompleted
            End If
            Me.InvokeAsync("ADD_DATA", New Object() {xml, PDF_TRADER, XML_TRADER, CITIZEN_ID, SOURCH, SOURCH_ID, LOT_CHK, IDA}, Me.ADD_DATAOperationCompleted, userState)
        End Sub
        
        Private Sub OnADD_DATAOperationCompleted(ByVal arg As Object)
            If (Not (Me.ADD_DATACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ADD_DATACompleted(Me, New ADD_DATACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class fileds_COMPLAIN_CLASS
        
        Private registerField As String
        
        Private drg_nameField As String
        
        Private cREATE_DATEField As Date
        
        Private cREATE_BYField As String
        
        '''<remarks/>
        Public Property register() As String
            Get
                Return Me.registerField
            End Get
            Set
                Me.registerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property drg_name() As String
            Get
                Return Me.drg_nameField
            End Get
            Set
                Me.drg_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CREATE_DATE() As Date
            Get
                Return Me.cREATE_DATEField
            End Get
            Set
                Me.cREATE_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CREATE_BY() As String
            Get
                Return Me.cREATE_BYField
            End Get
            Set
                Me.cREATE_BYField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class COMPLAIN_MA
        
        Private iDAField As Integer
        
        Private pATH_XMLField As String
        
        Private pATH_PDFField As String
        
        Private dRUG_NMField As String
        
        Private dRUG_NMMField As String
        
        Private dRUG_FORMATField As String
        
        Private dRUG_FORMAT_OTHERField As String
        
        Private dRUG_CRITICONField As String
        
        Private dRUG_TYPE_CONTField As String
        
        Private dRUG_REGISTERField As String
        
        Private dRUG_MANUFField As String
        
        Private dRUG_COUNTRYField As String
        
        Private dRUG_IMPNMField As String
        
        Private dRUG_DEALERField As String
        
        Private dRUG_DISTField As String
        
        Private dRUG_DIST_OTHERField As String
        
        Private dRUG_STCONDIField As String
        
        Private dRUG_STCONDI_OTHERField As String
        
        Private dATE_DETECTField As System.Nullable(Of Date)
        
        Private dATE_DETECT_THField As String
        
        Private dATE_FIND_CHKField As String
        
        Private dATE_FIND_CHK_OTHERField As String
        
        Private cOMPLAIN_BYField As String
        
        Private pOSITIONField As String
        
        Private dEPARTMENTField As String
        
        Private fULL_ADDRField As String
        
        Private tELField As String
        
        Private tEL1Field As String
        
        Private eMAILField As String
        
        Private lINE_IDField As String
        
        Private cREATE_DATEField As System.Nullable(Of Date)
        
        Private cREATE_BYField As String
        
        Private cREATE_BY_THField As String
        
        Private tR_IDField As String
        
        Private pHYSICAL1Field As System.Nullable(Of Integer)
        
        Private pHYSICAL2Field As System.Nullable(Of Integer)
        
        Private pHYSICAL3Field As System.Nullable(Of Integer)
        
        Private pHYSICAL4Field As System.Nullable(Of Integer)
        
        Private pHYSICAL5Field As System.Nullable(Of Integer)
        
        Private pHYSICAL6Field As System.Nullable(Of Integer)
        
        Private pHYSICAL7Field As System.Nullable(Of Integer)
        
        Private pHYSICAL8Field As System.Nullable(Of Integer)
        
        Private pHYSICAL9Field As System.Nullable(Of Integer)
        
        Private pHYSICAL10Field As System.Nullable(Of Integer)
        
        Private pHYSICAL11Field As System.Nullable(Of Integer)
        
        Private pHYSICAL12Field As System.Nullable(Of Integer)
        
        Private pHYSICAL13Field As System.Nullable(Of Integer)
        
        Private pHYSICAL13_OTHERField As String
        
        Private cONTRAINERField As System.Nullable(Of Integer)
        
        Private cONTRAINER_TEXTField As String
        
        Private lABELField As System.Nullable(Of Integer)
        
        Private lABEL_INPUT1Field As String
        
        Private lABEL_INPUT2Field As String
        
        Private lABEL_INPUT3Field As String
        
        Private iNFORMField As System.Nullable(Of Integer)
        
        Private aNALYSISField As System.Nullable(Of Integer)
        
        Private aNALYSIS_INPUT1Field As String
        
        Private aNALYSIS_INPUT2Field As String
        
        Private aNALYSIS_INPUT3Field As String
        
        Private oTHER_PLOBLEMField As String
        
        Private eX_PLOBLEMField As String
        
        Private eX_PLOBLEM_TEXTField As String
        
        Private eX_DRUGField As String
        
        Private eX_PICField As String
        
        Private iNFORM_NAMEField As String
        
        Private iNFORM_TELField As String
        
        Private iNFORM_TEL1Field As String
        
        Private iNFORM_EMAILField As String
        
        Private pRE_ACTIONField As String
        
        Private cITIZEN_IDField As String
        
        Private sTATUS_DATEField As System.Nullable(Of Date)
        
        Private rEMARKField As String
        
        Private sYSTEM_IDField As String
        
        Private iDENTIFYField As String
        
        Private sOURCHField As String
        
        Private sOURCH_IDField As String
        
        Private lOT_CHKField As String
        
        Private rECALL_STATUSField As String
        
        Private cOLOR_STATUSField As String
        
        Private sTATUS_IDField As String
        
        Private sTATUSField As String
        
        '''<remarks/>
        Public Property IDA() As Integer
            Get
                Return Me.iDAField
            End Get
            Set
                Me.iDAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PATH_XML() As String
            Get
                Return Me.pATH_XMLField
            End Get
            Set
                Me.pATH_XMLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PATH_PDF() As String
            Get
                Return Me.pATH_PDFField
            End Get
            Set
                Me.pATH_PDFField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_NM() As String
            Get
                Return Me.dRUG_NMField
            End Get
            Set
                Me.dRUG_NMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_NMM() As String
            Get
                Return Me.dRUG_NMMField
            End Get
            Set
                Me.dRUG_NMMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_FORMAT() As String
            Get
                Return Me.dRUG_FORMATField
            End Get
            Set
                Me.dRUG_FORMATField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_FORMAT_OTHER() As String
            Get
                Return Me.dRUG_FORMAT_OTHERField
            End Get
            Set
                Me.dRUG_FORMAT_OTHERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_CRITICON() As String
            Get
                Return Me.dRUG_CRITICONField
            End Get
            Set
                Me.dRUG_CRITICONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_TYPE_CONT() As String
            Get
                Return Me.dRUG_TYPE_CONTField
            End Get
            Set
                Me.dRUG_TYPE_CONTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_REGISTER() As String
            Get
                Return Me.dRUG_REGISTERField
            End Get
            Set
                Me.dRUG_REGISTERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_MANUF() As String
            Get
                Return Me.dRUG_MANUFField
            End Get
            Set
                Me.dRUG_MANUFField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_COUNTRY() As String
            Get
                Return Me.dRUG_COUNTRYField
            End Get
            Set
                Me.dRUG_COUNTRYField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_IMPNM() As String
            Get
                Return Me.dRUG_IMPNMField
            End Get
            Set
                Me.dRUG_IMPNMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_DEALER() As String
            Get
                Return Me.dRUG_DEALERField
            End Get
            Set
                Me.dRUG_DEALERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_DIST() As String
            Get
                Return Me.dRUG_DISTField
            End Get
            Set
                Me.dRUG_DISTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_DIST_OTHER() As String
            Get
                Return Me.dRUG_DIST_OTHERField
            End Get
            Set
                Me.dRUG_DIST_OTHERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_STCONDI() As String
            Get
                Return Me.dRUG_STCONDIField
            End Get
            Set
                Me.dRUG_STCONDIField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DRUG_STCONDI_OTHER() As String
            Get
                Return Me.dRUG_STCONDI_OTHERField
            End Get
            Set
                Me.dRUG_STCONDI_OTHERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DATE_DETECT() As System.Nullable(Of Date)
            Get
                Return Me.dATE_DETECTField
            End Get
            Set
                Me.dATE_DETECTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DATE_DETECT_TH() As String
            Get
                Return Me.dATE_DETECT_THField
            End Get
            Set
                Me.dATE_DETECT_THField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DATE_FIND_CHK() As String
            Get
                Return Me.dATE_FIND_CHKField
            End Get
            Set
                Me.dATE_FIND_CHKField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DATE_FIND_CHK_OTHER() As String
            Get
                Return Me.dATE_FIND_CHK_OTHERField
            End Get
            Set
                Me.dATE_FIND_CHK_OTHERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COMPLAIN_BY() As String
            Get
                Return Me.cOMPLAIN_BYField
            End Get
            Set
                Me.cOMPLAIN_BYField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property POSITION() As String
            Get
                Return Me.pOSITIONField
            End Get
            Set
                Me.pOSITIONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DEPARTMENT() As String
            Get
                Return Me.dEPARTMENTField
            End Get
            Set
                Me.dEPARTMENTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FULL_ADDR() As String
            Get
                Return Me.fULL_ADDRField
            End Get
            Set
                Me.fULL_ADDRField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TEL() As String
            Get
                Return Me.tELField
            End Get
            Set
                Me.tELField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TEL1() As String
            Get
                Return Me.tEL1Field
            End Get
            Set
                Me.tEL1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EMAIL() As String
            Get
                Return Me.eMAILField
            End Get
            Set
                Me.eMAILField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LINE_ID() As String
            Get
                Return Me.lINE_IDField
            End Get
            Set
                Me.lINE_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CREATE_DATE() As System.Nullable(Of Date)
            Get
                Return Me.cREATE_DATEField
            End Get
            Set
                Me.cREATE_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CREATE_BY() As String
            Get
                Return Me.cREATE_BYField
            End Get
            Set
                Me.cREATE_BYField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CREATE_BY_TH() As String
            Get
                Return Me.cREATE_BY_THField
            End Get
            Set
                Me.cREATE_BY_THField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TR_ID() As String
            Get
                Return Me.tR_IDField
            End Get
            Set
                Me.tR_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL1() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL1Field
            End Get
            Set
                Me.pHYSICAL1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL2() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL2Field
            End Get
            Set
                Me.pHYSICAL2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL3() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL3Field
            End Get
            Set
                Me.pHYSICAL3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL4() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL4Field
            End Get
            Set
                Me.pHYSICAL4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL5() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL5Field
            End Get
            Set
                Me.pHYSICAL5Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL6() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL6Field
            End Get
            Set
                Me.pHYSICAL6Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL7() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL7Field
            End Get
            Set
                Me.pHYSICAL7Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL8() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL8Field
            End Get
            Set
                Me.pHYSICAL8Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL9() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL9Field
            End Get
            Set
                Me.pHYSICAL9Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL10() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL10Field
            End Get
            Set
                Me.pHYSICAL10Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL11() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL11Field
            End Get
            Set
                Me.pHYSICAL11Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL12() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL12Field
            End Get
            Set
                Me.pHYSICAL12Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PHYSICAL13() As System.Nullable(Of Integer)
            Get
                Return Me.pHYSICAL13Field
            End Get
            Set
                Me.pHYSICAL13Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PHYSICAL13_OTHER() As String
            Get
                Return Me.pHYSICAL13_OTHERField
            End Get
            Set
                Me.pHYSICAL13_OTHERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CONTRAINER() As System.Nullable(Of Integer)
            Get
                Return Me.cONTRAINERField
            End Get
            Set
                Me.cONTRAINERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CONTRAINER_TEXT() As String
            Get
                Return Me.cONTRAINER_TEXTField
            End Get
            Set
                Me.cONTRAINER_TEXTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property LABEL() As System.Nullable(Of Integer)
            Get
                Return Me.lABELField
            End Get
            Set
                Me.lABELField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LABEL_INPUT1() As String
            Get
                Return Me.lABEL_INPUT1Field
            End Get
            Set
                Me.lABEL_INPUT1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LABEL_INPUT2() As String
            Get
                Return Me.lABEL_INPUT2Field
            End Get
            Set
                Me.lABEL_INPUT2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LABEL_INPUT3() As String
            Get
                Return Me.lABEL_INPUT3Field
            End Get
            Set
                Me.lABEL_INPUT3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property INFORM() As System.Nullable(Of Integer)
            Get
                Return Me.iNFORMField
            End Get
            Set
                Me.iNFORMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ANALYSIS() As System.Nullable(Of Integer)
            Get
                Return Me.aNALYSISField
            End Get
            Set
                Me.aNALYSISField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ANALYSIS_INPUT1() As String
            Get
                Return Me.aNALYSIS_INPUT1Field
            End Get
            Set
                Me.aNALYSIS_INPUT1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ANALYSIS_INPUT2() As String
            Get
                Return Me.aNALYSIS_INPUT2Field
            End Get
            Set
                Me.aNALYSIS_INPUT2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ANALYSIS_INPUT3() As String
            Get
                Return Me.aNALYSIS_INPUT3Field
            End Get
            Set
                Me.aNALYSIS_INPUT3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OTHER_PLOBLEM() As String
            Get
                Return Me.oTHER_PLOBLEMField
            End Get
            Set
                Me.oTHER_PLOBLEMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EX_PLOBLEM() As String
            Get
                Return Me.eX_PLOBLEMField
            End Get
            Set
                Me.eX_PLOBLEMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EX_PLOBLEM_TEXT() As String
            Get
                Return Me.eX_PLOBLEM_TEXTField
            End Get
            Set
                Me.eX_PLOBLEM_TEXTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EX_DRUG() As String
            Get
                Return Me.eX_DRUGField
            End Get
            Set
                Me.eX_DRUGField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EX_PIC() As String
            Get
                Return Me.eX_PICField
            End Get
            Set
                Me.eX_PICField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property INFORM_NAME() As String
            Get
                Return Me.iNFORM_NAMEField
            End Get
            Set
                Me.iNFORM_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property INFORM_TEL() As String
            Get
                Return Me.iNFORM_TELField
            End Get
            Set
                Me.iNFORM_TELField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property INFORM_TEL1() As String
            Get
                Return Me.iNFORM_TEL1Field
            End Get
            Set
                Me.iNFORM_TEL1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property INFORM_EMAIL() As String
            Get
                Return Me.iNFORM_EMAILField
            End Get
            Set
                Me.iNFORM_EMAILField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PRE_ACTION() As String
            Get
                Return Me.pRE_ACTIONField
            End Get
            Set
                Me.pRE_ACTIONField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CITIZEN_ID() As String
            Get
                Return Me.cITIZEN_IDField
            End Get
            Set
                Me.cITIZEN_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property STATUS_DATE() As System.Nullable(Of Date)
            Get
                Return Me.sTATUS_DATEField
            End Get
            Set
                Me.sTATUS_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property REMARK() As String
            Get
                Return Me.rEMARKField
            End Get
            Set
                Me.rEMARKField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SYSTEM_ID() As String
            Get
                Return Me.sYSTEM_IDField
            End Get
            Set
                Me.sYSTEM_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDENTIFY() As String
            Get
                Return Me.iDENTIFYField
            End Get
            Set
                Me.iDENTIFYField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SOURCH() As String
            Get
                Return Me.sOURCHField
            End Get
            Set
                Me.sOURCHField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SOURCH_ID() As String
            Get
                Return Me.sOURCH_IDField
            End Get
            Set
                Me.sOURCH_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LOT_CHK() As String
            Get
                Return Me.lOT_CHKField
            End Get
            Set
                Me.lOT_CHKField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RECALL_STATUS() As String
            Get
                Return Me.rECALL_STATUSField
            End Get
            Set
                Me.rECALL_STATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COLOR_STATUS() As String
            Get
                Return Me.cOLOR_STATUSField
            End Get
            Set
                Me.cOLOR_STATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property STATUS_ID() As String
            Get
                Return Me.sTATUS_IDField
            End Get
            Set
                Me.sTATUS_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property STATUS() As String
            Get
                Return Me.sTATUSField
            End Get
            Set
                Me.sTATUSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub INSERT_DATACompletedEventHandler(ByVal sender As Object, ByVal e As INSERT_DATACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class INSERT_DATACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub GET_DATA_COMPLAINCompletedEventHandler(ByVal sender As Object, ByVal e As GET_DATA_COMPLAINCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GET_DATA_COMPLAINCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As COMPLAIN_MA()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),COMPLAIN_MA())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub SV_CONNECT_COMPLAINCompletedEventHandler(ByVal sender As Object, ByVal e As SV_CONNECT_COMPLAINCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SV_CONNECT_COMPLAINCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")>  _
    Public Delegate Sub ADD_DATACompletedEventHandler(ByVal sender As Object, ByVal e As ADD_DATACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ADD_DATACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
End Namespace
